package com.project.clixify_backend_sb.repository;

import com.project.clixify_backend_sb.models.User;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

public interface UserRepository extends JpaRepository<User, Long>
{
    //We are adding a method to fetch the User from database with the help of their username, as there is no default method for this in JpaRepository, for which the query will be generated by Spring JPA.
    Optional<User> findByUsername(String username);
}
